esphome:
  name: crowpanel-35-test
  friendly_name: CrowPanel 3.5" Test

substitutions:
  home_page: lighting_1

packages:
  common: !include common.yaml
  device: !include devices/DIS05035H.yaml
  layout: !include layouts/480x320.yaml
