substitutions:
  device_name: sunton-50-test
  friendly_name: Sunton 5.0" Test
  home_page: lighting

packages:
  common: !include templates/common.yaml
  device: !include templates/devices/ESP32-8048S050.yaml
  layout: !include templates/layouts/800x480.yaml
