binary_sensor:
  - id: ${uid}_switch
    platform: homeassistant
    entity_id: ${entity_id}
    publish_initial_state: true
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_on: ${uid}_switch
            then:
              - lvgl.widget.update:
                  id: ${uid}_btn_icon
                  text_color: 0xFFD700
            else:
              - lvgl.widget.update:
                  id: ${uid}_btn_icon
                  text_color: 0xFFFFFF
